rel-3-7-10

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1251,7 +1251,7 @@ fi
 
 # Define the identity of the package.
 PACKAGE=gnugo
-VERSION=3.7.9
+VERSION=3.7.10
 
 cat >>confdefs.h <<EOF
 #define PACKAGE "$PACKAGE"
@@ -4212,10 +4212,14 @@ else
   cat >conftest.$ac_ext <<_ACEOF
 #line 4213 "configure"
 #include "confdefs.h"
+#if !defined(_WIN32) && !defined(_WIN32_WCE)
 #include <sys/socket.h>
 #include <netinet/in.h>
 #include <arpa/inet.h>
 #include <netdb.h>
+#else	/* on Windows */
+#include <winsock.h>
+#endif	/* on Windows */
 int
 main ()
 {
@@ -4235,16 +4239,16 @@ main ()
 }
 _ACEOF
 rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:4238: \"$ac_link\"") >&5
+if { (eval echo "$as_me:4242: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
-  echo "$as_me:4241: \$? = $ac_status" >&5
+  echo "$as_me:4245: \$? = $ac_status" >&5
   (exit $ac_status); } &&
          { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:4244: \"$ac_try\"") >&5
+  { (eval echo "$as_me:4248: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
-  echo "$as_me:4247: \$? = $ac_status" >&5
+  echo "$as_me:4251: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   gnugo_cv_sockets_supported="yes"
 else
@@ -4254,7 +4258,7 @@ gnugo_cv_sockets_supported="no"
 fi
 rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
 fi
-echo "$as_me:4257: result: $gnugo_cv_sockets_supported" >&5
+echo "$as_me:4261: result: $gnugo_cv_sockets_supported" >&5
 echo "${ECHO_T}$gnugo_cv_sockets_supported" >&6
 
   if test "$gnugo_cv_sockets_supported" = "yes"; then
@@ -4264,7 +4268,7 @@ EOF
 
   else
     if test "$enable_socket_support" = "yes"; then
-      { { echo "$as_me:4267: error:
+      { { echo "$as_me:4271: error:
 *** Socket support was requested, but cannot be compiled on your system. ***
 *** If you think this is a mistake, please report it to <gnugo@gnu.org>. ***" >&5
 echo "$as_me: error:
@@ -4272,7 +4276,7 @@ echo "$as_me: error:
 *** If you think this is a mistake, please report it to <gnugo@gnu.org>. ***" >&2;}
    { (exit 1); exit 1; }; };
     else
-      { echo "$as_me:4275: WARNING:
+      { echo "$as_me:4279: WARNING:
 *** Unable to compile socket support on your system.  It will be disabled. ***
 ***  If you think this is a mistake, please report it to <gnugo@gnu.org>.  ***" >&5
 echo "$as_me: WARNING:
@@ -4365,7 +4369,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:4368: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:4372: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -4541,7 +4545,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:4544: error: ambiguous option: $1
+    { { echo "$as_me:4548: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4560,7 +4564,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:4563: error: unrecognized option: $1
+  -*) { { echo "$as_me:4567: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -4616,7 +4620,7 @@ do
   "config.vc" ) CONFIG_FILES="$CONFIG_FILES config.vc:config.vcin" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4619: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4623: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4855,7 +4859,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4858: creating $ac_file" >&5
+    { echo "$as_me:4862: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4873,7 +4877,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4876: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4880: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4886,7 +4890,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4889: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4893: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4947,7 +4951,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4950: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4954: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4958,7 +4962,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4961: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4965: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4971,7 +4975,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4974: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4978: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5088,7 +5092,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5091: $ac_file is unchanged" >&5
+      { echo "$as_me:5095: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
